export const ROOT_DIR = '.infio_json_db'
export const COMMAND_DIR = 'commands'
export const CHAT_DIR = 'chats'
export const CUSTOM_MODE_DIR = 'custom_modes'
export const CONVERT_DATA_DIR = 'convert_data'
export const WORKSPACE_DIR = 'workspaces'
export const INITIAL_MIGRATION_MARKER = '.initial_migration_completed'
